package com.mdove.levelgame.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.DropGoods;

import com.mdove.levelgame.greendao.entity.BigMonsters;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BIG_MONSTERS".
*/
public class BigMonstersDao extends AbstractDao<BigMonsters, Long> {

    public static final String TABLENAME = "BIG_MONSTERS";

    /**
     * Properties of entity BigMonsters.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property Attack = new Property(3, int.class, "attack", false, "ATTACK");
        public final static Property Armor = new Property(4, int.class, "armor", false, "ARMOR");
        public final static Property Life = new Property(5, int.class, "life", false, "LIFE");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property MonsterPlaceId = new Property(7, long.class, "monsterPlaceId", false, "MONSTER_PLACE_ID");
        public final static Property Exp = new Property(8, long.class, "exp", false, "EXP");
        public final static Property Money = new Property(9, int.class, "money", false, "MONEY");
        public final static Property DropGoodsId = new Property(10, Long.class, "dropGoodsId", false, "DROP_GOODS_ID");
        public final static Property ConsumePower = new Property(11, long.class, "consumePower", false, "CONSUME_POWER");
        public final static Property IsGone = new Property(12, int.class, "isGone", false, "IS_GONE");
        public final static Property IsDead = new Property(13, int.class, "isDead", false, "IS_DEAD");
    }

    private DaoSession daoSession;


    public BigMonstersDao(DaoConfig config) {
        super(config);
    }
    
    public BigMonstersDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BIG_MONSTERS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"ATTACK\" INTEGER NOT NULL ," + // 3: attack
                "\"ARMOR\" INTEGER NOT NULL ," + // 4: armor
                "\"LIFE\" INTEGER NOT NULL ," + // 5: life
                "\"TYPE\" TEXT," + // 6: type
                "\"MONSTER_PLACE_ID\" INTEGER NOT NULL ," + // 7: monsterPlaceId
                "\"EXP\" INTEGER NOT NULL ," + // 8: exp
                "\"MONEY\" INTEGER NOT NULL ," + // 9: money
                "\"DROP_GOODS_ID\" INTEGER," + // 10: dropGoodsId
                "\"CONSUME_POWER\" INTEGER NOT NULL ," + // 11: consumePower
                "\"IS_GONE\" INTEGER NOT NULL ," + // 12: isGone
                "\"IS_DEAD\" INTEGER NOT NULL );"); // 13: isDead
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BIG_MONSTERS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BigMonsters entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
        stmt.bindLong(4, entity.getAttack());
        stmt.bindLong(5, entity.getArmor());
        stmt.bindLong(6, entity.getLife());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getMonsterPlaceId());
        stmt.bindLong(9, entity.getExp());
        stmt.bindLong(10, entity.getMoney());
 
        Long dropGoodsId = entity.getDropGoodsId();
        if (dropGoodsId != null) {
            stmt.bindLong(11, dropGoodsId);
        }
        stmt.bindLong(12, entity.getConsumePower());
        stmt.bindLong(13, entity.getIsGone());
        stmt.bindLong(14, entity.getIsDead());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BigMonsters entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
        stmt.bindLong(4, entity.getAttack());
        stmt.bindLong(5, entity.getArmor());
        stmt.bindLong(6, entity.getLife());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getMonsterPlaceId());
        stmt.bindLong(9, entity.getExp());
        stmt.bindLong(10, entity.getMoney());
 
        Long dropGoodsId = entity.getDropGoodsId();
        if (dropGoodsId != null) {
            stmt.bindLong(11, dropGoodsId);
        }
        stmt.bindLong(12, entity.getConsumePower());
        stmt.bindLong(13, entity.getIsGone());
        stmt.bindLong(14, entity.getIsDead());
    }

    @Override
    protected final void attachEntity(BigMonsters entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BigMonsters readEntity(Cursor cursor, int offset) {
        BigMonsters entity = new BigMonsters( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.getInt(offset + 3), // attack
            cursor.getInt(offset + 4), // armor
            cursor.getInt(offset + 5), // life
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.getLong(offset + 7), // monsterPlaceId
            cursor.getLong(offset + 8), // exp
            cursor.getInt(offset + 9), // money
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // dropGoodsId
            cursor.getLong(offset + 11), // consumePower
            cursor.getInt(offset + 12), // isGone
            cursor.getInt(offset + 13) // isDead
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BigMonsters entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAttack(cursor.getInt(offset + 3));
        entity.setArmor(cursor.getInt(offset + 4));
        entity.setLife(cursor.getInt(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMonsterPlaceId(cursor.getLong(offset + 7));
        entity.setExp(cursor.getLong(offset + 8));
        entity.setMoney(cursor.getInt(offset + 9));
        entity.setDropGoodsId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setConsumePower(cursor.getLong(offset + 11));
        entity.setIsGone(cursor.getInt(offset + 12));
        entity.setIsDead(cursor.getInt(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BigMonsters entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BigMonsters entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BigMonsters entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDropGoodsDao().getAllColumns());
            builder.append(" FROM BIG_MONSTERS T");
            builder.append(" LEFT JOIN DROP_GOODS T0 ON T.\"DROP_GOODS_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BigMonsters loadCurrentDeep(Cursor cursor, boolean lock) {
        BigMonsters entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DropGoods dropGoods = loadCurrentOther(daoSession.getDropGoodsDao(), cursor, offset);
        entity.setDropGoods(dropGoods);

        return entity;    
    }

    public BigMonsters loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BigMonsters> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BigMonsters> list = new ArrayList<BigMonsters>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BigMonsters> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BigMonsters> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
