package com.mdove.levelgame.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mdove.levelgame.greendao.entity.Armors;
import com.mdove.levelgame.greendao.entity.DropGoods;
import com.mdove.levelgame.greendao.entity.HeroAttributes;
import com.mdove.levelgame.greendao.entity.Medicines;
import com.mdove.levelgame.greendao.entity.Monsters;
import com.mdove.levelgame.greendao.entity.MonstersPlace;
import com.mdove.levelgame.greendao.entity.Weapons;

import com.mdove.levelgame.greendao.ArmorsDao;
import com.mdove.levelgame.greendao.DropGoodsDao;
import com.mdove.levelgame.greendao.HeroAttributesDao;
import com.mdove.levelgame.greendao.MedicinesDao;
import com.mdove.levelgame.greendao.MonstersDao;
import com.mdove.levelgame.greendao.MonstersPlaceDao;
import com.mdove.levelgame.greendao.WeaponsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig armorsDaoConfig;
    private final DaoConfig dropGoodsDaoConfig;
    private final DaoConfig heroAttributesDaoConfig;
    private final DaoConfig medicinesDaoConfig;
    private final DaoConfig monstersDaoConfig;
    private final DaoConfig monstersPlaceDaoConfig;
    private final DaoConfig weaponsDaoConfig;

    private final ArmorsDao armorsDao;
    private final DropGoodsDao dropGoodsDao;
    private final HeroAttributesDao heroAttributesDao;
    private final MedicinesDao medicinesDao;
    private final MonstersDao monstersDao;
    private final MonstersPlaceDao monstersPlaceDao;
    private final WeaponsDao weaponsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        armorsDaoConfig = daoConfigMap.get(ArmorsDao.class).clone();
        armorsDaoConfig.initIdentityScope(type);

        dropGoodsDaoConfig = daoConfigMap.get(DropGoodsDao.class).clone();
        dropGoodsDaoConfig.initIdentityScope(type);

        heroAttributesDaoConfig = daoConfigMap.get(HeroAttributesDao.class).clone();
        heroAttributesDaoConfig.initIdentityScope(type);

        medicinesDaoConfig = daoConfigMap.get(MedicinesDao.class).clone();
        medicinesDaoConfig.initIdentityScope(type);

        monstersDaoConfig = daoConfigMap.get(MonstersDao.class).clone();
        monstersDaoConfig.initIdentityScope(type);

        monstersPlaceDaoConfig = daoConfigMap.get(MonstersPlaceDao.class).clone();
        monstersPlaceDaoConfig.initIdentityScope(type);

        weaponsDaoConfig = daoConfigMap.get(WeaponsDao.class).clone();
        weaponsDaoConfig.initIdentityScope(type);

        armorsDao = new ArmorsDao(armorsDaoConfig, this);
        dropGoodsDao = new DropGoodsDao(dropGoodsDaoConfig, this);
        heroAttributesDao = new HeroAttributesDao(heroAttributesDaoConfig, this);
        medicinesDao = new MedicinesDao(medicinesDaoConfig, this);
        monstersDao = new MonstersDao(monstersDaoConfig, this);
        monstersPlaceDao = new MonstersPlaceDao(monstersPlaceDaoConfig, this);
        weaponsDao = new WeaponsDao(weaponsDaoConfig, this);

        registerDao(Armors.class, armorsDao);
        registerDao(DropGoods.class, dropGoodsDao);
        registerDao(HeroAttributes.class, heroAttributesDao);
        registerDao(Medicines.class, medicinesDao);
        registerDao(Monsters.class, monstersDao);
        registerDao(MonstersPlace.class, monstersPlaceDao);
        registerDao(Weapons.class, weaponsDao);
    }
    
    public void clear() {
        armorsDaoConfig.clearIdentityScope();
        dropGoodsDaoConfig.clearIdentityScope();
        heroAttributesDaoConfig.clearIdentityScope();
        medicinesDaoConfig.clearIdentityScope();
        monstersDaoConfig.clearIdentityScope();
        monstersPlaceDaoConfig.clearIdentityScope();
        weaponsDaoConfig.clearIdentityScope();
    }

    public ArmorsDao getArmorsDao() {
        return armorsDao;
    }

    public DropGoodsDao getDropGoodsDao() {
        return dropGoodsDao;
    }

    public HeroAttributesDao getHeroAttributesDao() {
        return heroAttributesDao;
    }

    public MedicinesDao getMedicinesDao() {
        return medicinesDao;
    }

    public MonstersDao getMonstersDao() {
        return monstersDao;
    }

    public MonstersPlaceDao getMonstersPlaceDao() {
        return monstersPlaceDao;
    }

    public WeaponsDao getWeaponsDao() {
        return weaponsDao;
    }

}
