package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.FbPlace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FB_PLACE".
*/
public class FbPlaceDao extends AbstractDao<FbPlace, Long> {

    public static final String TABLENAME = "FB_PLACE";

    /**
     * Properties of entity FbPlace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property IsLimitCount = new Property(4, int.class, "isLimitCount", false, "IS_LIMIT_COUNT");
        public final static Property LimitCount = new Property(5, int.class, "limitCount", false, "LIMIT_COUNT");
        public final static Property CurCount = new Property(6, int.class, "curCount", false, "CUR_COUNT");
        public final static Property ConsumePower = new Property(7, int.class, "consumePower", false, "CONSUME_POWER");
        public final static Property FbPlaceId = new Property(8, long.class, "fbPlaceId", false, "FB_PLACE_ID");
    }


    public FbPlaceDao(DaoConfig config) {
        super(config);
    }
    
    public FbPlaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FB_PLACE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"TYPE\" TEXT," + // 3: type
                "\"IS_LIMIT_COUNT\" INTEGER NOT NULL ," + // 4: isLimitCount
                "\"LIMIT_COUNT\" INTEGER NOT NULL ," + // 5: limitCount
                "\"CUR_COUNT\" INTEGER NOT NULL ," + // 6: curCount
                "\"CONSUME_POWER\" INTEGER NOT NULL ," + // 7: consumePower
                "\"FB_PLACE_ID\" INTEGER NOT NULL );"); // 8: fbPlaceId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FB_PLACE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FbPlace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getIsLimitCount());
        stmt.bindLong(6, entity.getLimitCount());
        stmt.bindLong(7, entity.getCurCount());
        stmt.bindLong(8, entity.getConsumePower());
        stmt.bindLong(9, entity.getFbPlaceId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FbPlace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getIsLimitCount());
        stmt.bindLong(6, entity.getLimitCount());
        stmt.bindLong(7, entity.getCurCount());
        stmt.bindLong(8, entity.getConsumePower());
        stmt.bindLong(9, entity.getFbPlaceId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FbPlace readEntity(Cursor cursor, int offset) {
        FbPlace entity = new FbPlace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.getInt(offset + 4), // isLimitCount
            cursor.getInt(offset + 5), // limitCount
            cursor.getInt(offset + 6), // curCount
            cursor.getInt(offset + 7), // consumePower
            cursor.getLong(offset + 8) // fbPlaceId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FbPlace entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsLimitCount(cursor.getInt(offset + 4));
        entity.setLimitCount(cursor.getInt(offset + 5));
        entity.setCurCount(cursor.getInt(offset + 6));
        entity.setConsumePower(cursor.getInt(offset + 7));
        entity.setFbPlaceId(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FbPlace entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FbPlace entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FbPlace entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
