package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.LiLianLevel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LI_LIAN_LEVEL".
*/
public class LiLianLevelDao extends AbstractDao<LiLianLevel, Long> {

    public static final String TABLENAME = "LI_LIAN_LEVEL";

    /**
     * Properties of entity LiLianLevel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property NeedLiLian = new Property(4, int.class, "needLiLian", false, "NEED_LI_LIAN");
        public final static Property UnlockType = new Property(5, String.class, "unlockType", false, "UNLOCK_TYPE");
        public final static Property BtnName = new Property(6, String.class, "btnName", false, "BTN_NAME");
    }


    public LiLianLevelDao(DaoConfig config) {
        super(config);
    }
    
    public LiLianLevelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LI_LIAN_LEVEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"TYPE\" TEXT," + // 3: type
                "\"NEED_LI_LIAN\" INTEGER NOT NULL ," + // 4: needLiLian
                "\"UNLOCK_TYPE\" TEXT," + // 5: unlockType
                "\"BTN_NAME\" TEXT);"); // 6: btnName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LI_LIAN_LEVEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LiLianLevel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getNeedLiLian());
 
        String unlockType = entity.getUnlockType();
        if (unlockType != null) {
            stmt.bindString(6, unlockType);
        }
 
        String btnName = entity.getBtnName();
        if (btnName != null) {
            stmt.bindString(7, btnName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LiLianLevel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getNeedLiLian());
 
        String unlockType = entity.getUnlockType();
        if (unlockType != null) {
            stmt.bindString(6, unlockType);
        }
 
        String btnName = entity.getBtnName();
        if (btnName != null) {
            stmt.bindString(7, btnName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LiLianLevel readEntity(Cursor cursor, int offset) {
        LiLianLevel entity = new LiLianLevel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.getInt(offset + 4), // needLiLian
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // unlockType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // btnName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LiLianLevel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNeedLiLian(cursor.getInt(offset + 4));
        entity.setUnlockType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBtnName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LiLianLevel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LiLianLevel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LiLianLevel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
