package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.MainMenu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAIN_MENU".
*/
public class MainMenuDao extends AbstractDao<MainMenu, Long> {

    public static final String TABLENAME = "MAIN_MENU";

    /**
     * Properties of entity MainMenu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property ClickId = new Property(3, Long.class, "clickId", false, "CLICK_ID");
        public final static Property BtnText = new Property(4, String.class, "btnText", false, "BTN_TEXT");
        public final static Property Type = new Property(5, String.class, "type", false, "TYPE");
        public final static Property Position = new Property(6, int.class, "position", false, "POSITION");
    }


    public MainMenuDao(DaoConfig config) {
        super(config);
    }
    
    public MainMenuDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAIN_MENU\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"CLICK_ID\" INTEGER," + // 3: clickId
                "\"BTN_TEXT\" TEXT," + // 4: btnText
                "\"TYPE\" TEXT," + // 5: type
                "\"POSITION\" INTEGER NOT NULL );"); // 6: position
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAIN_MENU\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MainMenu entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        Long clickId = entity.getClickId();
        if (clickId != null) {
            stmt.bindLong(4, clickId);
        }
 
        String btnText = entity.getBtnText();
        if (btnText != null) {
            stmt.bindString(5, btnText);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
        stmt.bindLong(7, entity.getPosition());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MainMenu entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        Long clickId = entity.getClickId();
        if (clickId != null) {
            stmt.bindLong(4, clickId);
        }
 
        String btnText = entity.getBtnText();
        if (btnText != null) {
            stmt.bindString(5, btnText);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
        stmt.bindLong(7, entity.getPosition());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MainMenu readEntity(Cursor cursor, int offset) {
        MainMenu entity = new MainMenu( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // clickId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // btnText
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // type
            cursor.getInt(offset + 6) // position
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MainMenu entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClickId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setBtnText(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPosition(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MainMenu entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MainMenu entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MainMenu entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
