package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.Medicines;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICINES".
*/
public class MedicinesDao extends AbstractDao<Medicines, Long> {

    public static final String TABLENAME = "MEDICINES";

    /**
     * Properties of entity Medicines.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property Life = new Property(3, int.class, "life", false, "LIFE");
        public final static Property LifeUp = new Property(4, int.class, "lifeUp", false, "LIFE_UP");
        public final static Property Price = new Property(5, int.class, "price", false, "PRICE");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property Attack = new Property(7, long.class, "attack", false, "ATTACK");
        public final static Property Armor = new Property(8, long.class, "armor", false, "ARMOR");
        public final static Property LimitCount = new Property(9, int.class, "limitCount", false, "LIMIT_COUNT");
        public final static Property IsLimitCount = new Property(10, int.class, "isLimitCount", false, "IS_LIMIT_COUNT");
        public final static Property IsLock = new Property(11, int.class, "isLock", false, "IS_LOCK");
        public final static Property CurCount = new Property(12, int.class, "curCount", false, "CUR_COUNT");
    }


    public MedicinesDao(DaoConfig config) {
        super(config);
    }
    
    public MedicinesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICINES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"LIFE\" INTEGER NOT NULL ," + // 3: life
                "\"LIFE_UP\" INTEGER NOT NULL ," + // 4: lifeUp
                "\"PRICE\" INTEGER NOT NULL ," + // 5: price
                "\"TYPE\" TEXT," + // 6: type
                "\"ATTACK\" INTEGER NOT NULL ," + // 7: attack
                "\"ARMOR\" INTEGER NOT NULL ," + // 8: armor
                "\"LIMIT_COUNT\" INTEGER NOT NULL ," + // 9: limitCount
                "\"IS_LIMIT_COUNT\" INTEGER NOT NULL ," + // 10: isLimitCount
                "\"IS_LOCK\" INTEGER NOT NULL ," + // 11: isLock
                "\"CUR_COUNT\" INTEGER NOT NULL );"); // 12: curCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICINES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Medicines entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
        stmt.bindLong(4, entity.getLife());
        stmt.bindLong(5, entity.getLifeUp());
        stmt.bindLong(6, entity.getPrice());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getAttack());
        stmt.bindLong(9, entity.getArmor());
        stmt.bindLong(10, entity.getLimitCount());
        stmt.bindLong(11, entity.getIsLimitCount());
        stmt.bindLong(12, entity.getIsLock());
        stmt.bindLong(13, entity.getCurCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Medicines entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
        stmt.bindLong(4, entity.getLife());
        stmt.bindLong(5, entity.getLifeUp());
        stmt.bindLong(6, entity.getPrice());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getAttack());
        stmt.bindLong(9, entity.getArmor());
        stmt.bindLong(10, entity.getLimitCount());
        stmt.bindLong(11, entity.getIsLimitCount());
        stmt.bindLong(12, entity.getIsLock());
        stmt.bindLong(13, entity.getCurCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Medicines readEntity(Cursor cursor, int offset) {
        Medicines entity = new Medicines( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.getInt(offset + 3), // life
            cursor.getInt(offset + 4), // lifeUp
            cursor.getInt(offset + 5), // price
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.getLong(offset + 7), // attack
            cursor.getLong(offset + 8), // armor
            cursor.getInt(offset + 9), // limitCount
            cursor.getInt(offset + 10), // isLimitCount
            cursor.getInt(offset + 11), // isLock
            cursor.getInt(offset + 12) // curCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Medicines entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLife(cursor.getInt(offset + 3));
        entity.setLifeUp(cursor.getInt(offset + 4));
        entity.setPrice(cursor.getInt(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAttack(cursor.getLong(offset + 7));
        entity.setArmor(cursor.getLong(offset + 8));
        entity.setLimitCount(cursor.getInt(offset + 9));
        entity.setIsLimitCount(cursor.getInt(offset + 10));
        entity.setIsLock(cursor.getInt(offset + 11));
        entity.setCurCount(cursor.getInt(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Medicines entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Medicines entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Medicines entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
