package com.mdove.levelgame.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.Weapons;

import com.mdove.levelgame.greendao.entity.MyWeapons;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_WEAPONS".
*/
public class MyWeaponsDao extends AbstractDao<MyWeapons, Long> {

    public static final String TABLENAME = "MY_WEAPONS";

    /**
     * Properties of entity MyWeapons.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WeaponsId = new Property(1, Long.class, "weaponsId", false, "WEAPONS_ID");
        public final static Property Strengthen = new Property(2, int.class, "strengthen", false, "STRENGTHEN");
    }

    private DaoSession daoSession;


    public MyWeaponsDao(DaoConfig config) {
        super(config);
    }
    
    public MyWeaponsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_WEAPONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WEAPONS_ID\" INTEGER," + // 1: weaponsId
                "\"STRENGTHEN\" INTEGER NOT NULL );"); // 2: strengthen
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_WEAPONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyWeapons entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long weaponsId = entity.getWeaponsId();
        if (weaponsId != null) {
            stmt.bindLong(2, weaponsId);
        }
        stmt.bindLong(3, entity.getStrengthen());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyWeapons entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long weaponsId = entity.getWeaponsId();
        if (weaponsId != null) {
            stmt.bindLong(2, weaponsId);
        }
        stmt.bindLong(3, entity.getStrengthen());
    }

    @Override
    protected final void attachEntity(MyWeapons entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MyWeapons readEntity(Cursor cursor, int offset) {
        MyWeapons entity = new MyWeapons( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // weaponsId
            cursor.getInt(offset + 2) // strengthen
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyWeapons entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWeaponsId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setStrengthen(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyWeapons entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyWeapons entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyWeapons entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWeaponsDao().getAllColumns());
            builder.append(" FROM MY_WEAPONS T");
            builder.append(" LEFT JOIN WEAPONS T0 ON T.\"WEAPONS_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MyWeapons loadCurrentDeep(Cursor cursor, boolean lock) {
        MyWeapons entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Weapons weapons = loadCurrentOther(daoSession.getWeaponsDao(), cursor, offset);
        entity.setWeapons(weapons);

        return entity;    
    }

    public MyWeapons loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MyWeapons> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MyWeapons> list = new ArrayList<MyWeapons>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MyWeapons> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MyWeapons> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
