package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.Packages;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PACKAGES".
*/
public class PackagesDao extends AbstractDao<Packages, Long> {

    public static final String TABLENAME = "PACKAGES";

    /**
     * Properties of entity Packages.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property IsEquip = new Property(2, int.class, "isEquip", false, "IS_EQUIP");
        public final static Property StrengthenLevel = new Property(3, int.class, "strengthenLevel", false, "STRENGTHEN_LEVEL");
        public final static Property IsSelect = new Property(4, int.class, "isSelect", false, "IS_SELECT");
    }


    public PackagesDao(DaoConfig config) {
        super(config);
    }
    
    public PackagesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PACKAGES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" TEXT," + // 1: type
                "\"IS_EQUIP\" INTEGER NOT NULL ," + // 2: isEquip
                "\"STRENGTHEN_LEVEL\" INTEGER NOT NULL ," + // 3: strengthenLevel
                "\"IS_SELECT\" INTEGER NOT NULL );"); // 4: isSelect
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PACKAGES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Packages entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindLong(3, entity.getIsEquip());
        stmt.bindLong(4, entity.getStrengthenLevel());
        stmt.bindLong(5, entity.getIsSelect());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Packages entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindLong(3, entity.getIsEquip());
        stmt.bindLong(4, entity.getStrengthenLevel());
        stmt.bindLong(5, entity.getIsSelect());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Packages readEntity(Cursor cursor, int offset) {
        Packages entity = new Packages( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.getInt(offset + 2), // isEquip
            cursor.getInt(offset + 3), // strengthenLevel
            cursor.getInt(offset + 4) // isSelect
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Packages entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsEquip(cursor.getInt(offset + 2));
        entity.setStrengthenLevel(cursor.getInt(offset + 3));
        entity.setIsSelect(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Packages entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Packages entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Packages entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
