package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.PracticePlace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRACTICE_PLACE".
*/
public class PracticePlaceDao extends AbstractDao<PracticePlace, Long> {

    public static final String TABLENAME = "PRACTICE_PLACE";

    /**
     * Properties of entity PracticePlace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property IsLimitCount = new Property(4, int.class, "isLimitCount", false, "IS_LIMIT_COUNT");
        public final static Property LimitCount = new Property(5, int.class, "limitCount", false, "LIMIT_COUNT");
        public final static Property CurCount = new Property(6, int.class, "curCount", false, "CUR_COUNT");
        public final static Property ConsumeMoney = new Property(7, int.class, "consumeMoney", false, "CONSUME_MONEY");
        public final static Property ConsumePower = new Property(8, int.class, "consumePower", false, "CONSUME_POWER");
        public final static Property ConsumeGoods = new Property(9, String.class, "consumeGoods", false, "CONSUME_GOODS");
    }


    public PracticePlaceDao(DaoConfig config) {
        super(config);
    }
    
    public PracticePlaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRACTICE_PLACE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"TYPE\" TEXT," + // 3: type
                "\"IS_LIMIT_COUNT\" INTEGER NOT NULL ," + // 4: isLimitCount
                "\"LIMIT_COUNT\" INTEGER NOT NULL ," + // 5: limitCount
                "\"CUR_COUNT\" INTEGER NOT NULL ," + // 6: curCount
                "\"CONSUME_MONEY\" INTEGER NOT NULL ," + // 7: consumeMoney
                "\"CONSUME_POWER\" INTEGER NOT NULL ," + // 8: consumePower
                "\"CONSUME_GOODS\" TEXT);"); // 9: consumeGoods
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRACTICE_PLACE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PracticePlace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getIsLimitCount());
        stmt.bindLong(6, entity.getLimitCount());
        stmt.bindLong(7, entity.getCurCount());
        stmt.bindLong(8, entity.getConsumeMoney());
        stmt.bindLong(9, entity.getConsumePower());
 
        String consumeGoods = entity.getConsumeGoods();
        if (consumeGoods != null) {
            stmt.bindString(10, consumeGoods);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PracticePlace entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
        stmt.bindLong(5, entity.getIsLimitCount());
        stmt.bindLong(6, entity.getLimitCount());
        stmt.bindLong(7, entity.getCurCount());
        stmt.bindLong(8, entity.getConsumeMoney());
        stmt.bindLong(9, entity.getConsumePower());
 
        String consumeGoods = entity.getConsumeGoods();
        if (consumeGoods != null) {
            stmt.bindString(10, consumeGoods);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PracticePlace readEntity(Cursor cursor, int offset) {
        PracticePlace entity = new PracticePlace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.getInt(offset + 4), // isLimitCount
            cursor.getInt(offset + 5), // limitCount
            cursor.getInt(offset + 6), // curCount
            cursor.getInt(offset + 7), // consumeMoney
            cursor.getInt(offset + 8), // consumePower
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // consumeGoods
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PracticePlace entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsLimitCount(cursor.getInt(offset + 4));
        entity.setLimitCount(cursor.getInt(offset + 5));
        entity.setCurCount(cursor.getInt(offset + 6));
        entity.setConsumeMoney(cursor.getInt(offset + 7));
        entity.setConsumePower(cursor.getInt(offset + 8));
        entity.setConsumeGoods(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PracticePlace entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PracticePlace entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PracticePlace entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
