package com.mdove.levelgame.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mdove.levelgame.greendao.entity.Weapons;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEAPONS".
*/
public class WeaponsDao extends AbstractDao<Weapons, Long> {

    public static final String TABLENAME = "WEAPONS";

    /**
     * Properties of entity Weapons.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Tips = new Property(2, String.class, "tips", false, "TIPS");
        public final static Property Attack = new Property(3, int.class, "attack", false, "ATTACK");
        public final static Property Armor = new Property(4, int.class, "armor", false, "ARMOR");
        public final static Property Price = new Property(5, long.class, "price", false, "PRICE");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property IsCanStrengthen = new Property(7, int.class, "isCanStrengthen", false, "IS_CAN_STRENGTHEN");
        public final static Property IsCanUpdate = new Property(8, int.class, "isCanUpdate", false, "IS_CAN_UPDATE");
        public final static Property IsCanMixture = new Property(9, int.class, "isCanMixture", false, "IS_CAN_MIXTURE");
        public final static Property IsSpecial = new Property(10, int.class, "isSpecial", false, "IS_SPECIAL");
        public final static Property MixtureFormula = new Property(11, String.class, "mixtureFormula", false, "MIXTURE_FORMULA");
        public final static Property UpdateFormula = new Property(12, String.class, "updateFormula", false, "UPDATE_FORMULA");
        public final static Property StrengthenFormula = new Property(13, String.class, "strengthenFormula", false, "STRENGTHEN_FORMULA");
        public final static Property BelongMonsterId = new Property(14, String.class, "belongMonsterId", false, "BELONG_MONSTER_ID");
    }


    public WeaponsDao(DaoConfig config) {
        super(config);
    }
    
    public WeaponsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEAPONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TIPS\" TEXT," + // 2: tips
                "\"ATTACK\" INTEGER NOT NULL ," + // 3: attack
                "\"ARMOR\" INTEGER NOT NULL ," + // 4: armor
                "\"PRICE\" INTEGER NOT NULL ," + // 5: price
                "\"TYPE\" TEXT," + // 6: type
                "\"IS_CAN_STRENGTHEN\" INTEGER NOT NULL ," + // 7: isCanStrengthen
                "\"IS_CAN_UPDATE\" INTEGER NOT NULL ," + // 8: isCanUpdate
                "\"IS_CAN_MIXTURE\" INTEGER NOT NULL ," + // 9: isCanMixture
                "\"IS_SPECIAL\" INTEGER NOT NULL ," + // 10: isSpecial
                "\"MIXTURE_FORMULA\" TEXT," + // 11: mixtureFormula
                "\"UPDATE_FORMULA\" TEXT," + // 12: updateFormula
                "\"STRENGTHEN_FORMULA\" TEXT," + // 13: strengthenFormula
                "\"BELONG_MONSTER_ID\" TEXT);"); // 14: belongMonsterId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEAPONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Weapons entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
        stmt.bindLong(4, entity.getAttack());
        stmt.bindLong(5, entity.getArmor());
        stmt.bindLong(6, entity.getPrice());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getIsCanStrengthen());
        stmt.bindLong(9, entity.getIsCanUpdate());
        stmt.bindLong(10, entity.getIsCanMixture());
        stmt.bindLong(11, entity.getIsSpecial());
 
        String mixtureFormula = entity.getMixtureFormula();
        if (mixtureFormula != null) {
            stmt.bindString(12, mixtureFormula);
        }
 
        String updateFormula = entity.getUpdateFormula();
        if (updateFormula != null) {
            stmt.bindString(13, updateFormula);
        }
 
        String strengthenFormula = entity.getStrengthenFormula();
        if (strengthenFormula != null) {
            stmt.bindString(14, strengthenFormula);
        }
 
        String belongMonsterId = entity.getBelongMonsterId();
        if (belongMonsterId != null) {
            stmt.bindString(15, belongMonsterId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Weapons entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(3, tips);
        }
        stmt.bindLong(4, entity.getAttack());
        stmt.bindLong(5, entity.getArmor());
        stmt.bindLong(6, entity.getPrice());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getIsCanStrengthen());
        stmt.bindLong(9, entity.getIsCanUpdate());
        stmt.bindLong(10, entity.getIsCanMixture());
        stmt.bindLong(11, entity.getIsSpecial());
 
        String mixtureFormula = entity.getMixtureFormula();
        if (mixtureFormula != null) {
            stmt.bindString(12, mixtureFormula);
        }
 
        String updateFormula = entity.getUpdateFormula();
        if (updateFormula != null) {
            stmt.bindString(13, updateFormula);
        }
 
        String strengthenFormula = entity.getStrengthenFormula();
        if (strengthenFormula != null) {
            stmt.bindString(14, strengthenFormula);
        }
 
        String belongMonsterId = entity.getBelongMonsterId();
        if (belongMonsterId != null) {
            stmt.bindString(15, belongMonsterId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Weapons readEntity(Cursor cursor, int offset) {
        Weapons entity = new Weapons( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tips
            cursor.getInt(offset + 3), // attack
            cursor.getInt(offset + 4), // armor
            cursor.getLong(offset + 5), // price
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.getInt(offset + 7), // isCanStrengthen
            cursor.getInt(offset + 8), // isCanUpdate
            cursor.getInt(offset + 9), // isCanMixture
            cursor.getInt(offset + 10), // isSpecial
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // mixtureFormula
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // updateFormula
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // strengthenFormula
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // belongMonsterId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Weapons entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTips(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAttack(cursor.getInt(offset + 3));
        entity.setArmor(cursor.getInt(offset + 4));
        entity.setPrice(cursor.getLong(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsCanStrengthen(cursor.getInt(offset + 7));
        entity.setIsCanUpdate(cursor.getInt(offset + 8));
        entity.setIsCanMixture(cursor.getInt(offset + 9));
        entity.setIsSpecial(cursor.getInt(offset + 10));
        entity.setMixtureFormula(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setUpdateFormula(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStrengthenFormula(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBelongMonsterId(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Weapons entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Weapons entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Weapons entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
